// ISO 3166-1 alpha-2 codes (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)
export const Regions = [
  "AD",
  "AE",
  "AF",
  "AG",
  "AI",
  "AL",
  "AM",
  "AO",
  "AQ",
  "AR",
  "AS",
  "AT",
  "AU",
  "AW",
  "AX",
  "AZ",
  "BA",
  "BB",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BL",
  "BM",
  "BN",
  "BO",
  "BQ",
  "BR",
  "BS",
  "BT",
  "BV",
  "BW",
  "BY",
  "BZ",
  "CA",
  "CC",
  "CD",
  "CF",
  "CG",
  "CH",
  "CI",
  "CK",
  "CL",
  "CM",
  "CN",
  "CO",
  "CR",
  "CU",
  "CV",
  "CW",
  "CX",
  "CY",
  "CZ",
  "DE",
  "DJ",
  "DK",
  "DM",
  "DO",
  "DZ",
  "EC",
  "EE",
  "EG",
  "EH",
  "ER",
  "ES",
  "ET",
  "FI",
  "FJ",
  "FK",
  "FM",
  "FO",
  "FR",
  "GA",
  "GB",
  "GD",
  "GE",
  "GF",
  "GG",
  "GH",
  "GI",
  "GL",
  "GM",
  "GN",
  "GP",
  "GQ",
  "GR",
  "GT",
  "GU",
  "GW",
  "GY",
  "HK",
  "HM",
  "HN",
  "HR",
  "HT",
  "HU",
  "ID",
  "IE",
  "IL",
  "IM",
  "IN",
  "IO",
  "IQ",
  "IR",
  "IS",
  "IT",
  "JE",
  "JM",
  "JO",
  "JP",
  "KE",
  "KG",
  "KH",
  "KI",
  "KM",
  "KN",
  "KP",
  "KR",
  "KW",
  "KY",
  "KZ",
  "LA",
  "LB",
  "LC",
  "LI",
  "LK",
  "LR",
  "LS",
  "LT",
  "LU",
  "LV",
  "LY",
  "MA",
  "MC",
  "MD",
  "ME",
  "MF",
  "MG",
  "MH",
  "MK",
  "ML",
  "MM",
  "MN",
  "MO",
  "MP",
  "MQ",
  "MR",
  "MS",
  "MT",
  "MU",
  "MV",
  "MW",
  "MX",
  "MY",
  "MZ",
  "NA",
  "NC",
  "NE",
  "NF",
  "NG",
  "NI",
  "NL",
  "NO",
  "NP",
  "NR",
  "NU",
  "NZ",
  "OM",
  "PA",
  "PE",
  "PF",
  "PG",
  "PH",
  "PK",
  "PL",
  "PM",
  "PN",
  "PR",
  "PT",
  "PW",
  "PY",
  "QA",
  "RE",
  "RO",
  "RS",
  "RU",
  "RW",
  "SA",
  "SB",
  "SC",
  "SD",
  "SE",
  "SG",
  "SH",
  "SI",
  "SJ",
  "SK",
  "SL",
  "SM",
  "SN",
  "SO",
  "SR",
  "SS",
  "ST",
  "SV",
  "SX",
  "SY",
  "SZ",
  "TC",
  "TD",
  "TF",
  "TG",
  "TH",
  "TJ",
  "TK",
  "TL",
  "TM",
  "TN",
  "TO",
  "TR",
  "TT",
  "TV",
  "TW",
  "TZ",
  "UA",
  "UG",
  "UM",
  "US",
  "UY",
  "UZ",
  "VA",
  "VC",
  "VE",
  "VG",
  "VI",
  "VN",
  "VU",
  "WF",
  "WS",
  "YE",
  "YT",
  "ZA",
  "ZM",
  "ZW",
];
export type Region = (typeof Regions)[number];
export const isRegion = (region: string): region is Region => Regions.includes(region as Region);

// Map country codes to country names
export const countryNamesEnglish: Record<Region, string> = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Åland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint Barthélemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BQ: "Bonaire",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos (Keeling) Islands",
  CD: "Democratic Republic of the Congo",
  CF: "Central African Republic",
  CG: "Republic of the Congo",
  CH: "Switzerland",
  CI: "Ivory Coast",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cape Verde",
  CW: "Curaçao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard Island and McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "Saint Kitts and Nevis",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "Saint Martin",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolia",
  MO: "Macau",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "Saint Pierre and Miquelon",
  PN: "Pitcairn Islands",
  PR: "Puerto Rico",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Réunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SH: "Saint Helena",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "São Tomé and Príncipe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SY: "Syria",
  SZ: "Eswatini",
  TC: "Turks and Caicos Islands",
  TD: "Chad",
  TF: "French Southern and Antarctic Lands",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Turkey",
  TT: "Trinidad and Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "United States Minor Outlying Islands",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Vatican City",
  VC: "Saint Vincent and the Grenadines",
  VE: "Venezuela",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  WS: "Samoa",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

export const countryNamesGerman: Record<Region, string> = {
  AD: "Andorra",
  AE: "Vereinigte Arabische Emirate",
  AF: "Afghanistan",
  AG: "Antigua und Barbuda",
  AI: "Anguilla",
  AL: "Albanien",
  AM: "Armenien",
  AO: "Angola",
  AQ: "Antarktis",
  AR: "Argentinien",
  AS: "Amerikanisch-Samoa",
  AT: "Österreich",
  AU: "Australien",
  AW: "Aruba",
  AX: "Ålandinseln",
  AZ: "Aserbaidschan",
  BA: "Bosnien und Herzegowina",
  BB: "Barbados",
  BD: "Bangladesch",
  BE: "Belgien",
  BF: "Burkina Faso",
  BG: "Bulgarien",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint-Barthélemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivien",
  BQ: "Bonaire",
  BR: "Brasilien",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvetinsel",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Kanada",
  CC: "Kokosinseln",
  CD: "Demokratische Republik Kongo",
  CF: "Zentralafrikanische Republik",
  CG: "Republik Kongo",
  CH: "Schweiz",
  CI: "Elfenbeinküste",
  CK: "Cookinseln",
  CL: "Chile",
  CM: "Kamerun",
  CN: "China",
  CO: "Kolumbien",
  CR: "Costa Rica",
  CU: "Kuba",
  CV: "Kap Verde",
  CW: "Curaçao",
  CX: "Weihnachtsinsel",
  CY: "Zypern",
  CZ: "Tschechien",
  DE: "Deutschland",
  DJ: "Dschibuti",
  DK: "Dänemark",
  DM: "Dominica",
  DO: "Dominikanische Republik",
  DZ: "Algerien",
  EC: "Ecuador",
  EE: "Estland",
  EG: "Ägypten",
  EH: "Westsahara",
  ER: "Eritrea",
  ES: "Spanien",
  ET: "Äthiopien",
  FI: "Finnland",
  FJ: "Fidschi",
  FK: "Falklandinseln",
  FM: "Mikronesien",
  FO: "Färöer",
  FR: "Frankreich",
  GA: "Gabun",
  GB: "Vereinigtes Königreich",
  GD: "Grenada",
  GE: "Georgien",
  GF: "Französisch-Guayana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Grönland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Äquatorialguinea",
  GR: "Griechenland",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hongkong",
  HM: "Heard und McDonaldinseln",
  HN: "Honduras",
  HR: "Kroatien",
  HT: "Haiti",
  HU: "Ungarn",
  ID: "Indonesien",
  IE: "Irland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "Indien",
  IO: "Britisches Territorium im Indischen Ozean",
  IQ: "Irak",
  IR: "Iran",
  IS: "Island",
  IT: "Italien",
  JE: "Jersey",
  JM: "Jamaika",
  JO: "Jordanien",
  JP: "Japan",
  KE: "Kenia",
  KG: "Kirgisistan",
  KH: "Kambodscha",
  KI: "Kiribati",
  KM: "Komoren",
  KN: "St. Kitts und Nevis",
  KP: "Nordkorea",
  KR: "Südkorea",
  KW: "Kuwait",
  KY: "Kaimaninseln",
  KZ: "Kasachstan",
  LA: "Laos",
  LB: "Libanon",
  LC: "St. Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Litauen",
  LU: "Luxemburg",
  LV: "Lettland",
  LY: "Libyen",
  MA: "Marokko",
  MC: "Monaco",
  MD: "Moldawien",
  ME: "Montenegro",
  MF: "Saint-Martin",
  MG: "Madagaskar",
  MH: "Marshallinseln",
  MK: "Nordmazedonien",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolei",
  MO: "Macau",
  MP: "Nördliche Marianen",
  MQ: "Martinique",
  MR: "Mauretanien",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Malediven",
  MW: "Malawi",
  MX: "Mexiko",
  MY: "Malaysia",
  MZ: "Mosambik",
  NA: "Namibia",
  NC: "Neukaledonien",
  NE: "Niger",
  NF: "Norfolkinsel",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Niederlande",
  NO: "Norwegen",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "Neuseeland",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "Französisch-Polynesien",
  PG: "Papua-Neuguinea",
  PH: "Philippinen",
  PK: "Pakistan",
  PL: "Polen",
  PM: "Saint-Pierre und Miquelon",
  PN: "Pitcairninseln",
  PR: "Puerto Rico",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Katar",
  RE: "Réunion",
  RO: "Rumänien",
  RS: "Serbien",
  RU: "Russland",
  RW: "Ruanda",
  SA: "Saudi-Arabien",
  SB: "Salomonen",
  SC: "Seychellen",
  SD: "Sudan",
  SE: "Schweden",
  SG: "Singapur",
  SH: "St. Helena",
  SI: "Slowenien",
  SJ: "Svalbard und Jan Mayen",
  SK: "Slowakei",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "Südsudan",
  ST: "São Tomé und Príncipe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SY: "Syrien",
  SZ: "Eswatini",
  TC: "Turks- und Caicosinseln",
  TD: "Tschad",
  TF: "Französische Süd- und Antarktisgebiete",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tadschikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunesien",
  TO: "Tonga",
  TR: "Türkei",
  TT: "Trinidad und Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tansania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "United States Minor Outlying Islands",
  US: "Vereinigte Staaten",
  UY: "Uruguay",
  UZ: "Usbekistan",
  VA: "Vatikanstadt",
  VC: "St. Vincent und die Grenadinen",
  VE: "Venezuela",
  VG: "Britische Jungferninseln",
  VI: "Amerikanische Jungferninseln",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis und Futuna",
  WS: "Samoa",
  YE: "Jemen",
  YT: "Mayotte",
  ZA: "Südafrika",
  ZM: "Sambia",
  ZW: "Simbabwe",
};

export const countryNamesSpanish: Record<string, string> = {
  AD: "Andorra",
  AE: "Emiratos Árabes Unidos",
  AF: "Afganistán",
  AG: "Antigua y Barbuda",
  AI: "Anguila",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antártida",
  AR: "Argentina",
  AS: "Samoa Americana",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Islas Åland",
  AZ: "Azerbaiyán",
  BA: "Bosnia y Herzegovina",
  BB: "Barbados",
  BD: "Bangladés",
  BE: "Bélgica",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Baréin",
  BI: "Burundi",
  BJ: "Benín",
  BL: "San Bartolomé",
  BM: "Bermudas",
  BN: "Brunéi",
  BO: "Bolivia",
  BQ: "Bonaire",
  BR: "Brasil",
  BS: "Bahamas",
  BT: "Bután",
  BV: "Isla Bouvet",
  BW: "Botsuana",
  BY: "Bielorrusia",
  BZ: "Belice",
  CA: "Canadá",
  CC: "Islas Cocos",
  CD: "República Democrática del Congo",
  CF: "República Centroafricana",
  CG: "República del Congo",
  CH: "Suiza",
  CI: "Costa de Marfil",
  CK: "Islas Cook",
  CL: "Chile",
  CM: "Camerún",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cabo Verde",
  CW: "Curazao",
  CX: "Isla de Navidad",
  CY: "Chipre",
  CZ: "Chequia",
  DE: "Alemania",
  DJ: "Yibuti",
  DK: "Dinamarca",
  DM: "Dominica",
  DO: "República Dominicana",
  DZ: "Argelia",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egipto",
  EH: "Sahara Occidental",
  ER: "Eritrea",
  ES: "España",
  ET: "Etiopía",
  FI: "Finlandia",
  FJ: "Fiyi",
  FK: "Islas Malvinas",
  FM: "Micronesia",
  FO: "Islas Feroe",
  FR: "Francia",
  GA: "Gabón",
  GB: "Reino Unido",
  GD: "Granada",
  GE: "Georgia",
  GF: "Guayana Francesa",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Groenlandia",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadalupe",
  GQ: "Guinea Ecuatorial",
  GR: "Grecia",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bisáu",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Islas Heard y McDonald",
  HN: "Honduras",
  HR: "Croacia",
  HT: "Haití",
  HU: "Hungría",
  ID: "Indonesia",
  IE: "Irlanda",
  IL: "Israel",
  IM: "Isla de Man",
  IN: "India",
  IO: "Territorio Británico del Océano Índico",
  IQ: "Irak",
  IR: "Irán",
  IS: "Islandia",
  IT: "Italia",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordania",
  JP: "Japón",
  KE: "Kenia",
  KG: "Kirguistán",
  KH: "Camboya",
  KI: "Kiribati",
  KM: "Comoras",
  KN: "San Cristóbal y Nieves",
  KP: "Corea del Norte",
  KR: "Corea del Sur",
  KW: "Kuwait",
  KY: "Islas Caimán",
  KZ: "Kazajistán",
  LA: "Laos",
  LB: "Líbano",
  LC: "Santa Lucía",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesoto",
  LT: "Lituania",
  LU: "Luxemburgo",
  LV: "Letonia",
  LY: "Libia",
  MA: "Marruecos",
  MC: "Mónaco",
  MD: "Moldavia",
  ME: "Montenegro",
  MF: "San Martín",
  MG: "Madagascar",
  MH: "Islas Marshall",
  MK: "Macedonia del Norte",
  ML: "Malí",
  MM: "Birmania",
  MN: "Mongolia",
  MO: "Macao",
  MP: "Islas Marianas del Norte",
  MQ: "Martinica",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauricio",
  MV: "Maldivas",
  MW: "Malaui",
  MX: "México",
  MY: "Malasia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "Nueva Caledonia",
  NE: "Níger",
  NF: "Isla Norfolk",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Países Bajos",
  NO: "Noruega",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "Nueva Zelanda",
  OM: "Omán",
  PA: "Panamá",
  PE: "Perú",
  PF: "Polinesia Francesa",
  PG: "Papúa Nueva Guinea",
  PH: "Filipinas",
  PK: "Pakistán",
  PL: "Polonia",
  PM: "San Pedro y Miquelón",
  PN: "Islas Pitcairn",
  PR: "Puerto Rico",
  PT: "Portugal",
  PW: "Palaos",
  PY: "Paraguay",
  QA: "Catar",
  RE: "Reunión",
  RO: "Rumanía",
  RS: "Serbia",
  RU: "Rusia",
  RW: "Ruanda",
  SA: "Arabia Saudita",
  SB: "Islas Salomón",
  SC: "Seychelles",
  SD: "Sudán",
  SE: "Suecia",
  SG: "Singapur",
  SH: "Santa Elena",
  SI: "Eslovenia",
  SJ: "Svalbard y Jan Mayen",
  SK: "Eslovaquia",
  SL: "Sierra Leona",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Surinam",
  SS: "Sudán del Sur",
  ST: "Santo Tomé y Príncipe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SY: "Siria",
  SZ: "Esuatini",
  TC: "Islas Turcas y Caicos",
  TD: "Chad",
  TF: "Territorios Australes Franceses",
  TG: "Togo",
  TH: "Tailandia",
  TJ: "Tayikistán",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistán",
  TN: "Túnez",
  TO: "Tonga",
  TR: "Turquía",
  TT: "Trinidad y Tobago",
  TV: "Tuvalu",
  TW: "Taiwán",
  TZ: "Tanzania",
  UA: "Ucrania",
  UG: "Uganda",
  UM: "Islas Ultramarinas Menores de Estados Unidos",
  US: "Estados Unidos",
  UY: "Uruguay",
  UZ: "Uzbekistán",
  VA: "Ciudad del Vaticano",
  VC: "San Vicente y las Granadinas",
  VE: "Venezuela",
  VG: "Islas Vírgenes Británicas",
  VI: "Islas Vírgenes de los Estados Unidos",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis y Futuna",
  WS: "Samoa",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "Sudáfrica",
  ZM: "Zambia",
  ZW: "Zimbabue",
};
